import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopNavBar from "./components/TopNavBar";
import Footer from "./components/Footer";

// Initialize the Google fonts with variables for CSS usage
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


// Define metadata for the entire app (used for SEO and browser tab titles)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout wraps every page in the app
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      {/* 
        min-h-screen → ensures page is at least the full viewport height (100vh)
        flex + flex-col → vertical stacking (Navbar → Content → Footer)
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}
      >
        
        <TopNavBar />

        <main className="flex-grow ">{children}</main>


        {/* 
          flex-grow → makes content area expand to fill leftover space 
          ensures the footer stays at the bottom when content is short.
        */}

        <footer className="footer footer-horizontal footer-center bg-base-200 text-base-content rounded p-10">
          <Footer />
        </footer>

      </body>
    </html>
  );
}
